/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconExpand: typeof import('./src/components/icon-expand/index.vue')['default']
    IconFold: typeof import('./src/components/icon-fold/index.vue')['default']
    IconSearch: typeof import('./src/components/icon-search/index.vue')['default']
    PageX: typeof import('./src/components/PageX/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const IconExpand: typeof import('./src/components/icon-expand/index.vue')['default']
  const IconFold: typeof import('./src/components/icon-fold/index.vue')['default']
  const IconSearch: typeof import('./src/components/icon-search/index.vue')['default']
  const PageX: typeof import('./src/components/PageX/index.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}